Fix default value of pythonIFD module
The option `yk8s._pythonIFD` didn't have a default value, but there is
an assertion that references it. So if the option was not set, it could
happen that evaluation failed with:

error: The option `perSystem.x86_64-linux.yk8s._pythonIFD.functions' was
accessed but has no value defined. Try setting the option.

This commit adds the missing default value so evaluation succeeds
without defining Python functions.