Add ansible-lint v6.14.6 compliance
Debian, the base our CI image, updated Python packages in its 11.7
release. This led to the circumstance, that ansible-lint v6.11.0 fails [1].
Therefore, we should update the ansible-lint version. This requires us
to make tasks compliant as ansible-lint no detects more errors than
previously.

Ignore all tasks which can not be fixed ad-hoc.

[1] with: AttributeError: 'str' object has no attribute 'resolve'